export * from './config'
export * from './deferred'
export * from './deferredCallback'
export * from './deferredFetch'
export * from './deferredPost'
export * from './delay'
export * from './delayReject'
export * from './fetch'
export * from './mergeFetchOptions'
export * from './PromisE'
export * from './PromisEBase'
export * from './post'
export * from './timeout'
export * from './types'
import PromisE from './PromisE'

export default PromisE
